# -*- coding: utf-8 -*-
"""Lab_Activity_1_Decision_Tree_Induction_using_Information_Gain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4Qg6ZSkR5Q-ajic8FEaPKElJ-0deJBX

Decision Tree Induction using Information Gain
"""

# Required Packages

import math
import pandas as pd

"""Step 1: Load the Dataset"""

# Upload the dataset in the google colab and load the dataset.

dataset = pd.read_csv('LabActivity1.csv')
print(dataset)

"""Step 2: Working of Decision Tree Induction"""

# Count the Class Labels

class_counts = dataset['buys_computer'].value_counts()

print("Class Label Counts:")
print(class_counts)

print("\nTotal Samples:", len(dataset))

"""Step 3: Calculate Entropy(S)"""

# First Term of Information Gain - Calculate Entropy(S)

yes = 9
no = 5
total = 14

p_yes = yes / total
p_no = no / total

entropy_S = -(p_yes * math.log2(p_yes)) - (p_no * math.log2(p_no))

print("Probability of Yes =", p_yes)
print("Probability of No  =", p_no)
print("Entropy(S) =", round(entropy_S, 4))

# Count Samples for each attribute value

# Age Attribute
print("AGE ATTRIBUTE")
age_counts = dataset.groupby(['age', 'buys_computer']).size()
print(age_counts)

# Income Attribute
print("\nINCOME ATTRIBUTE")
income_counts = dataset.groupby(['income', 'buys_computer']).size()
print(income_counts)

# Student Attribute
print("\nSTUDENT ATTRIBUTE")
student_counts = dataset.groupby(['student', 'buys_computer']).size()
print(student_counts)

# Credit Rating Attribute
print("\nCREDIT RATING ATTRIBUTE")
creditrating_counts = dataset.groupby(['credit_rating', 'buys_computer']).size()
print(creditrating_counts)

"""Step 4: Calculate Entropy(S|attribute)"""

# Calculate Entropy for Each Attribute Value

def calculate_entropy(yes, no):
    total = yes + no

    # If the subset contains only one class
    if yes == 0 or no == 0:
        return 0

    p_yes = yes / total
    p_no = no / total

    entropy = -(p_yes * math.log2(p_yes)) - \
              (p_no * math.log2(p_no))

    return entropy


# Age Attribute

entropy_age_30 = calculate_entropy(2, 3)
entropy_age_31_40 = calculate_entropy(4, 0)
entropy_age_40 = calculate_entropy(3, 2)

print("Entropy(age <=30)    =", round(entropy_age_30, 3))
print("Entropy(age 31...40) =", round(entropy_age_31_40, 3))
print("Entropy(age >40)     =", round(entropy_age_40, 3))

# Income Attribute
entropy_income_high = calculate_entropy(2, 2)
entropy_income_medium = calculate_entropy(4, 2)
entropy_income_low = calculate_entropy(3, 1)

print("Entropy(income = high)   =", round(entropy_income_high, 3))
print("Entropy(income = medium) =", round(entropy_income_medium, 3))
print("Entropy(income = low)    =", round(entropy_income_low, 3))


# Student Attribute

entropy_student_no = calculate_entropy(3, 4)
entropy_student_yes = calculate_entropy(6, 1)

print("Entropy(student = no)  =", round(entropy_student_no, 3))
print("Entropy(student = yes) =", round(entropy_student_yes, 3))


# Credit Rating Attribute

entropy_credit_fair = calculate_entropy(6, 2)
entropy_credit_excellent = calculate_entropy(3, 3)

print("Entropy(credit_rating = fair)      =", round(entropy_credit_fair, 3))
print("Entropy(credit_rating = excellent) =", round(entropy_credit_excellent, 3))

# Calculate Weighted Entropy for Each Attribute

# Age
weighted_entropy_age = (
    (5/14) * entropy_age_30 +
    (4/14) * entropy_age_31_40 +
    (5/14) * entropy_age_40
)

# Income
weighted_entropy_income = (
    (4/14) * entropy_income_high +
    (6/14) * entropy_income_medium +
    (4/14) * entropy_income_low
)

# Student
weighted_entropy_student = (
    (7/14) * entropy_student_no +
    (7/14) * entropy_student_yes
)

# Credit Rating
weighted_entropy_credit = (
    (8/14) * entropy_credit_fair +
    (6/14) * entropy_credit_excellent
)

# Display Results
print("Weighted Entropy(S | Age)           =",
      round(weighted_entropy_age, 4))

print("Weighted Entropy(S | Income)        =",
      round(weighted_entropy_income, 4))

print("Weighted Entropy(S | Student)       =",
      round(weighted_entropy_student, 4))

print("Weighted Entropy(S | Credit Rating) =",
      round(weighted_entropy_credit, 4))

"""Step 5: Calculate IG (S|attribute)"""

# Calculate Information Gain for All Attributes

IG_age = entropy_S - weighted_entropy_age
IG_income = entropy_S - weighted_entropy_income
IG_student = entropy_S - weighted_entropy_student
IG_credit = entropy_S - weighted_entropy_credit

print("Information Gain Results")
print("------------------------")

print("IG(S, Age)           =", round(IG_age, 4))
print("IG(S, Income)        =", round(IG_income, 4))
print("IG(S, Student)       =", round(IG_student, 4))
print("IG(S, Credit Rating) =", round(IG_credit, 4))

"""Step 6: Left Side"""

# Entropy for Age <= 30

entropy_age_30_subset = calculate_entropy(2, 3)

print("Entropy(Age <= 30) =", round(entropy_age_30_subset, 3))

# Information Gain for remaining attributes when Age <= 30

IG_income_age30 = entropy_age_30_subset - (
    (2/5) * calculate_entropy(0, 2) +
    (2/5) * calculate_entropy(1, 1) +
    (1/5) * calculate_entropy(1, 0)
)

IG_student_age30 = entropy_age_30_subset - (
    (3/5) * calculate_entropy(0, 3) +
    (2/5) * calculate_entropy(2, 0)
)

IG_credit_age30 = entropy_age_30_subset - (
    (3/5) * calculate_entropy(1, 2) +
    (2/5) * calculate_entropy(1, 1)
)

print("IG(Age <=30, Income)        =", round(IG_income_age30, 3))
print("IG(Age <=30, Student)       =", round(IG_student_age30, 3))
print("IG(Age <=30, Credit Rating) =", round(IG_credit_age30, 3))

# Split the Dataset Based on Age

age_30 = dataset[dataset['age'] == '<=30']
age_31_40 = dataset[dataset['age'] == '31...40']
age_40 = dataset[dataset['age'] == '>40']

print("Age <= 30:")
print(age_30)

print("\nAge = 31...40:")
print(age_31_40)

print("\nAge > 40:")
print(age_40)

# Split Age <= 30 by Student

age30_student_no = age_30[age_30['student'] == 'no']
age30_student_yes = age_30[age_30['student'] == 'yes']

print("Age <= 30 and Student = no")
print(age30_student_no['buys_computer'].value_counts())

print("\nAge <= 30 and Student = yes")
print(age30_student_yes['buys_computer'].value_counts())

"""Step 7: Right Side"""

# Entropy for Age > 40

entropy_age_40_subset = calculate_entropy(3, 2)

print("Entropy(Age > 40) =", round(entropy_age_40_subset, 3))

# Information Gain for remaining attributes when Age > 40

IG_income_age40 = entropy_age_40_subset - (
    (3/5) * calculate_entropy(2, 1) +
    (2/5) * calculate_entropy(1, 1)
)

IG_student_age40 = entropy_age_40_subset - (
    (2/5) * calculate_entropy(1, 1) +
    (3/5) * calculate_entropy(2, 1)
)

IG_credit_age40 = entropy_age_40_subset - (
    (3/5) * calculate_entropy(3, 0) +
    (2/5) * calculate_entropy(0, 2)
)

print("IG(Age >40, Income)        =", round(IG_income_age40, 3))
print("IG(Age >40, Student)       =", round(IG_student_age40, 3))
print("IG(Age >40, Credit Rating) =", round(IG_credit_age40, 3))

# Split Age > 40 by Credit Rating

age40_fair = age_40[age_40['credit_rating'] == 'fair']
age40_excellent = age_40[age_40['credit_rating'] == 'excellent']

print("Age > 40 and Credit Rating = fair")
print(age40_fair['buys_computer'].value_counts())

print("\nAge > 40 and Credit Rating = excellent")
print(age40_excellent['buys_computer'].value_counts())

"""Step 8: If-else rules constructed in the Training Phase"""

# Print Decision Rules

print("Decision Rules:")
print("-------------------------------")

print("1. If Age <= 30 and Student = no, then Buys Computer = NO")
print("2. If Age <= 30 and Student = yes, then Buys Computer = YES")
print("3. If Age = 31...40, then Buys Computer = YES")
print("4. If Age > 40 and Credit Rating = fair, then Buys Computer = YES")
print("5. If Age > 40 and Credit Rating = excellent, then Buys Computer = NO")