# -*- coding: utf-8 -*-
"""Lab Activity 1 - omurambiwa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vN1ADbDLkIfJvYouAv0kk8SKSBiXg45W
"""

# Required Packages

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import matplotlib.pyplot as plot

dataset = pd.read_csv("LabActivity1.csv")
print(dataset)

# Data Transformation

encoders = {}

for column in dataset.columns:
    if dataset[column].dtype == 'object':
        encoder = LabelEncoder()
        dataset[column] = encoder.fit_transform(dataset[column])
        encoders[column] = encoder

print(dataset)

X = dataset[['age', 'income', 'student', 'credit_rating']]
y = dataset['buys_computer']

# Create a Decision Tree

decision_tree = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=3,
    random_state=42
)

decision_tree.fit(X, y)

# Testing phase

test_data = pd.DataFrame({
    'age': ['<=30'],
    'income': ['medium'],
    'student': ['yes'],
    'credit_rating': ['fair']
})

print(test_data)